import type { ComparisonArticle } from "./types"
import { COMPARISON_SLUGS } from "./slugs"

type LocaleCopy = { titles: string[]; description: string; verdict: string }
const localeCopy: Record<string, LocaleCopy> = {
  fr: { titles: ["MP3 ou FLAC — écoute ou archivage ?", "JPG ou WebP — lequel pour le Web ?", "PDF ou DOCX — édition ou publication ?", "PNG ou JPG — photos ou graphismes ?", "MP4 ou WebM — universel ou Web ?", "HEIC ou JPG — iPhone et compatibilité"], description: "Comparez la qualité, la taille, la compatibilité et l’usage conseillé de ces deux formats.", verdict: "Choisissez le premier pour son usage principal et le second lorsque ses avantages de qualité ou de compatibilité répondent mieux à votre besoin." },
  it: { titles: ["MP3 o FLAC — ascolto o archivio?", "JPG o WebP — quale per il Web?", "PDF o DOCX — modifica o pubblicazione?", "PNG o JPG — foto o grafica?", "MP4 o WebM — universale o Web?", "HEIC o JPG — iPhone e compatibilità"], description: "Confronto tra qualità, dimensione, compatibilità e utilizzo consigliato dei due formati.", verdict: "Scegli il formato più adatto all’uso finale e conserva l’originale di qualità prima di convertire." },
  pt: { titles: ["MP3 ou FLAC — ouvir ou arquivar?", "JPG ou WebP — qual para a Web?", "PDF ou DOCX — editar ou publicar?", "PNG ou JPG — fotos ou gráficos?", "MP4 ou WebM — universal ou Web?", "HEIC ou JPG — iPhone e compatibilidade"], description: "Compare qualidade, tamanho, compatibilidade e utilização recomendada destes dois formatos.", verdict: "Escolha de acordo com o destino final e guarde o original de melhor qualidade antes de converter." },
  nl: { titles: ["MP3 of FLAC — luisteren of archiveren?", "JPG of WebP — welke voor het web?", "PDF of DOCX — bewerken of publiceren?", "PNG of JPG — foto’s of grafiek?", "MP4 of WebM — universeel of web?", "HEIC of JPG — iPhone en compatibiliteit"], description: "Vergelijk kwaliteit, bestandsgrootte, compatibiliteit en het aanbevolen gebruik van beide formaten.", verdict: "Kies op basis van het eindgebruik en bewaar vóór conversie altijd het origineel met de hoogste kwaliteit." },
  sv: { titles: ["MP3 eller FLAC – lyssna eller arkivera?", "JPG eller WebP – vad passar webben?", "PDF eller DOCX – redigera eller publicera?", "PNG eller JPG – foto eller grafik?", "MP4 eller WebM – universellt eller webb?", "HEIC eller JPG – iPhone och kompatibilitet"], description: "Jämför kvalitet, filstorlek, kompatibilitet och rekommenderad användning för de två formaten.", verdict: "Välj efter slutmålet och behåll alltid originalet med högst kvalitet före konvertering." },
  no: { titles: ["MP3 eller FLAC – lytting eller arkiv?", "JPG eller WebP – hva passer på nett?", "PDF eller DOCX – redigering eller publisering?", "PNG eller JPG – foto eller grafikk?", "MP4 eller WebM – universelt eller nett?", "HEIC eller JPG – iPhone og kompatibilitet"], description: "Sammenlign kvalitet, filstørrelse, kompatibilitet og anbefalt bruk for de to formatene.", verdict: "Velg etter sluttbruken, og behold alltid originalen med høyest kvalitet før konvertering." },
  da: { titles: ["MP3 eller FLAC – lytning eller arkiv?", "JPG eller WebP – hvad passer til web?", "PDF eller DOCX – redigering eller udgivelse?", "PNG eller JPG – foto eller grafik?", "MP4 eller WebM – universelt eller web?", "HEIC eller JPG – iPhone og kompatibilitet"], description: "Sammenlign kvalitet, filstørrelse, kompatibilitet og anbefalet brug af de to formater.", verdict: "Vælg efter slutformålet, og behold altid originalen i bedste kvalitet før konvertering." },
  fi: { titles: ["MP3 vai FLAC – kuuntelu vai arkisto?", "JPG vai WebP – kumpi verkkoon?", "PDF vai DOCX – muokkaus vai julkaisu?", "PNG vai JPG – kuvat vai grafiikka?", "MP4 vai WebM – yleinen vai verkko?", "HEIC vai JPG – iPhone ja yhteensopivuus"], description: "Vertaa kahden muodon laatua, tiedostokokoa, yhteensopivuutta ja suositeltua käyttöä.", verdict: "Valitse lopullisen käyttötavan mukaan ja säilytä paras alkuperäinen ennen muuntamista." },
  cs: { titles: ["MP3 nebo FLAC – poslech či archiv?", "JPG nebo WebP – co pro web?", "PDF nebo DOCX – úprava či publikace?", "PNG nebo JPG – fotky či grafika?", "MP4 nebo WebM – univerzální či web?", "HEIC nebo JPG – iPhone a kompatibilita"], description: "Porovnejte kvalitu, velikost, kompatibilitu a doporučené použití obou formátů.", verdict: "Volte podle cílového použití a před převodem vždy uchovejte nejkvalitnější originál." },
  ro: { titles: ["MP3 sau FLAC – ascultare ori arhivă?", "JPG sau WebP – ce alegem pentru Web?", "PDF sau DOCX – editare ori publicare?", "PNG sau JPG – fotografii ori grafică?", "MP4 sau WebM – universal ori Web?", "HEIC sau JPG – iPhone și compatibilitate"], description: "Comparați calitatea, dimensiunea, compatibilitatea și utilizarea recomandată a celor două formate.", verdict: "Alegeți după destinația finală și păstrați originalul de calitate maximă înainte de conversie." },
  hu: { titles: ["MP3 vagy FLAC – hallgatás vagy archívum?", "JPG vagy WebP – melyik webre?", "PDF vagy DOCX – szerkesztés vagy közzététel?", "PNG vagy JPG – fotó vagy grafika?", "MP4 vagy WebM – általános vagy webes?", "HEIC vagy JPG – iPhone és kompatibilitás"], description: "Hasonlítsa össze a két formátum minőségét, méretét, kompatibilitását és ajánlott használatát.", verdict: "A végső felhasználás alapján válasszon, és konvertálás előtt őrizze meg a legjobb eredetit." },
  el: { titles: ["MP3 ή FLAC – ακρόαση ή αρχείο;", "JPG ή WebP – ποιο για το Web;", "PDF ή DOCX – επεξεργασία ή δημοσίευση;", "PNG ή JPG – φωτογραφίες ή γραφικά;", "MP4 ή WebM – γενική χρήση ή Web;", "HEIC ή JPG – iPhone και συμβατότητα"], description: "Συγκρίνετε ποιότητα, μέγεθος, συμβατότητα και προτεινόμενη χρήση των δύο μορφών.", verdict: "Επιλέξτε με βάση την τελική χρήση και κρατήστε το καλύτερο πρωτότυπο πριν από τη μετατροπή." },
  tr: { titles: ["MP3 mü FLAC mı: dinleme mi arşiv mi?", "JPG mi WebP mi: Web için hangisi?", "PDF mi DOCX mi: düzenleme mi yayın mı?", "PNG mi JPG mi: fotoğraf mı grafik mi?", "MP4 mü WebM mi: evrensel mi Web mi?", "HEIC mi JPG mi: iPhone ve uyumluluk"], description: "İki biçimin kalitesini, boyutunu, uyumluluğunu ve önerilen kullanımını karşılaştırın.", verdict: "Son kullanıma göre seçim yapın ve dönüştürmeden önce en kaliteli özgün dosyayı saklayın." },
  ru: { titles: ["MP3 или FLAC — прослушивание или архив?", "JPG или WebP — что выбрать для сайта?", "PDF или DOCX — редактирование или публикация?", "PNG или JPG — фотографии или графика?", "MP4 или WebM — универсальность или Web?", "HEIC или JPG — iPhone и совместимость"], description: "Сравните качество, размер, совместимость и рекомендуемое применение двух форматов.", verdict: "Выбирайте по конечной задаче и всегда сохраняйте оригинал лучшего качества до конвертации." },
  ar: { titles: ["MP3 أم FLAC: استماع أم أرشفة؟", "JPG أم WebP: أيهما للويب؟", "PDF أم DOCX: تحرير أم نشر؟", "PNG أم JPG: صور أم رسومات؟", "MP4 أم WebM: عام أم للويب؟", "HEIC أم JPG: iPhone والتوافق"], description: "قارن الجودة والحجم والتوافق والاستخدام الموصى به للتنسيقين.", verdict: "اختر وفق الاستخدام النهائي واحتفظ دائمًا بالأصل الأعلى جودة قبل التحويل." },
  zh: { titles: ["MP3 与 FLAC：收听还是归档？", "JPG 与 WebP：网页该选哪个？", "PDF 与 DOCX：编辑还是发布？", "PNG 与 JPG：照片还是图形？", "MP4 与 WebM：通用还是网页？", "HEIC 与 JPG：iPhone 与兼容性"], description: "比较两种格式的质量、大小、兼容性和推荐用途。", verdict: "应根据最终用途选择，并在转换前保留质量最高的原件。" },
  ja: { titles: ["MP3とFLAC：再生か保存か", "JPGとWebP：Webにはどちら？", "PDFとDOCX：編集か公開か", "PNGとJPG：写真か図版か", "MP4とWebM：汎用かWebか", "HEICとJPG：iPhoneと互換性"], description: "2つの形式について品質、容量、互換性、適した用途を比較します。", verdict: "最終用途に合わせて選び、変換前に最高品質の原本を必ず保存してください。" },
  ko: { titles: ["MP3와 FLAC: 감상인가 보관인가?", "JPG와 WebP: 웹에는 무엇이 좋을까?", "PDF와 DOCX: 편집인가 배포인가?", "PNG와 JPG: 사진인가 그래픽인가?", "MP4와 WebM: 범용인가 웹인가?", "HEIC와 JPG: iPhone과 호환성"], description: "두 형식의 품질, 크기, 호환성, 권장 용도를 비교합니다.", verdict: "최종 용도에 맞게 선택하고 변환 전에는 가장 좋은 품질의 원본을 보관하세요." },
  hi: { titles: ["MP3 या FLAC: सुनना या संग्रह?", "JPG या WebP: वेब के लिए कौन?", "PDF या DOCX: संपादन या प्रकाशन?", "PNG या JPG: फोटो या ग्राफ़िक?", "MP4 या WebM: सार्वभौमिक या वेब?", "HEIC या JPG: iPhone और संगतता"], description: "दोनों प्रारूपों की गुणवत्ता, आकार, संगतता और सुझाए गए उपयोग की तुलना करें।", verdict: "अंतिम उपयोग के अनुसार चुनें और रूपांतरण से पहले सर्वोत्तम मूल फ़ाइल सुरक्षित रखें।" },
  id: { titles: ["MP3 atau FLAC: dengar atau arsip?", "JPG atau WebP: mana untuk Web?", "PDF atau DOCX: sunting atau terbitkan?", "PNG atau JPG: foto atau grafis?", "MP4 atau WebM: universal atau Web?", "HEIC atau JPG: iPhone dan kompatibilitas"], description: "Bandingkan mutu, ukuran, kompatibilitas, dan penggunaan yang disarankan untuk kedua format.", verdict: "Pilih sesuai tujuan akhir dan simpan sumber berkualitas terbaik sebelum mengonversi." },
}

const formats = [["mp3","flac"],["jpg","webp"],["pdf","docx"],["png","jpg"],["mp4","webm"],["heic","jpg"]]
const tools = [["mp3-to-flac","flac-to-mp3"],["jpg-to-webp","webp-to-jpg"],["docx-to-pdf","pdf-to-docx"],["png-to-jpg","jpg-to-png"],["mp4-to-webm","webm-to-mp4"],["heic-to-jpg"]]

export const localizedComparisonArticles: Record<string, Record<string, ComparisonArticle>> =
  Object.fromEntries(Object.entries(localeCopy).map(([locale, text]) => [locale,
    Object.fromEntries(COMPARISON_SLUGS.map((slug, i) => [slug, {
      slug, title: text.titles[i], description: text.description,
      formatA: formats[i][0], formatB: formats[i][1],
      sections: [
        { title: formats[i][0].toUpperCase(), paragraphs: [text.description] },
        { title: formats[i][1].toUpperCase(), paragraphs: [text.description] },
      ],
      verdict: text.verdict, relatedTools: tools[i],
    }]))
  ]))
