import type { LegalDocumentData } from "@/components/legal-document"

export const termsEn: LegalDocumentData = {
  eyebrow: "Terms of Service",
  title: "Terms of Service for Toolando.tech",
  intro:
    "These Terms of Service govern your use of the Toolando.tech website at toolando.tech. By using the Service — including browsing pages, uploading files, creating an account, or purchasing a Premium subscription — you accept these Terms in full. If you do not accept the Terms, do not use the Service.",
  lastUpdated: "Last updated: July 23, 2026",
  sections: [
    {
      title: "§1. General provisions",
      paragraphs: [
        "1.1. The owner and operator of Toolando.tech (the “Service”) is Szymon Badyl (the “Provider”).",
        "1.2. Contact: {{email}}. For matters requiring formal correspondence, the Provider will disclose identification details upon justified request, in accordance with applicable law.",
        "1.3. The Service provides browser-based online tools including file converters, specialist tools, AI-powered tools, and informational content (guides, FAQ).",
        "1.4. These Terms are made available free of charge on the Service in a form that allows downloading, saving, and printing.",
      ],
    },
    {
      title: "§2. Definitions",
      definitions: [
        {
          term: "User",
          description:
            "Any natural or legal person using the Service, including guests (without an account) and registered users.",
        },
        {
          term: "Account",
          description:
            "An individual User profile created to access features requiring registration, including Premium subscriptions.",
        },
        {
          term: "Free tools",
          description:
            "Service features available at no charge and without creating an Account, unless these Terms state otherwise.",
        },
        {
          term: "Premium",
          description:
            "A paid subscription providing access to extended features, including selected AI tools and higher limits.",
        },
        {
          term: "User file",
          description:
            "Any file, text content, or data uploaded by the User to a tool in the Service for processing.",
        },
        {
          term: "Generated content",
          description:
            "Results produced by Service tools, including converted files, text, or images generated by AI tools.",
        },
      ],
    },
    {
      title: "§3. Technical requirements and age",
      paragraphs: [
        "3.1. Using the Service requires a device with Internet access, a current web browser supporting JavaScript, and — for some tools — the ability to download files to your device.",
        "3.2. The Service is intended for persons aged 16 and over. Users under 16 may use the Service only with the consent and supervision of a parent or legal guardian.",
        "3.3. The User represents that they have full legal capacity or use the Service with a guardian's consent.",
      ],
    },
    {
      title: "§4. Scope of the Service",
      paragraphs: [
        "4.1. The Service is provided “as is”. The Provider makes reasonable efforts for tools to work correctly but does not guarantee uninterrupted availability, compatibility with all file formats, or any specific outcome.",
        "4.2. Some operations run locally in the User's browser (e.g. the universal file opener). Some require temporary server processing — details are in the Privacy Policy and the “How it works” page.",
        "4.3. The Provider may add, modify, limit, or remove tools, features, or file formats, including marking converters as “coming soon” or temporarily unavailable.",
        "4.4. Information in guides, FAQ, and tool descriptions is informational only and does not constitute professional legal, medical, financial, or technical advice.",
      ],
    },
    {
      title: "§5. User account",
      paragraphs: [
        "5.1. Creating an Account requires a valid email address and password. The User agrees to provide accurate information and keep it up to date.",
        "5.2. The User is responsible for keeping login credentials confidential and for all activity under their Account. If unauthorized access is suspected, contact {{email}} immediately.",
        "5.3. The Provider may suspend or delete an Account for Terms violations, suspected abuse, actions threatening Service security, or upon request by authorities, subject to applicable law.",
        "5.4. The User may stop using their Account at any time. Account deletion can be requested at {{email}}.",
      ],
    },
    {
      title: "§6. Free tools and Premium",
      paragraphs: [
        "6.1. Free tools are available at no charge. The Provider may apply technical limits (e.g. file size, number of operations) communicated in the Service interface.",
        "6.2. Premium is a recurring paid subscription for extended features including AI tools. The current Premium scope is shown on the Service before purchase.",
        "6.3. Premium fees are charged in advance for each billing period (e.g. monthly) via Stripe. Prices are shown in the currency indicated at checkout and include taxes where required by law.",
        "6.4. Premium can be cancelled at any time via the subscription management panel (Stripe Customer Portal) in the Account. Cancellation means the subscription will not renew after the current paid period — Premium access continues until that period ends.",
        "6.5. Fees for a started and paid subscription period are non-refundable unless mandatory consumer law requires otherwise. For technical failures preventing Premium use for an extended time, the User may submit a complaint to {{email}}.",
        "6.6. Consumers may have a 14-day right of withdrawal for distance contracts unless the Provider began Premium delivery with the User's express consent before the withdrawal period ended — in accordance with applicable EU/Polish consumer law. Starting Premium use before 14 days elapse may mean consent to immediate performance and loss of withdrawal rights to the extent permitted by law.",
      ],
    },
    {
      title: "§7. User files and data processing",
      paragraphs: [
        "7.1. Files uploaded to Service tools are used solely to perform the operation requested by the User (conversion, compression, preview, content generation, etc.).",
        "7.2. Server-processed files are not stored after the operation completes and are not used for other purposes, including AI model training, sale, or sharing with third parties.",
        "7.3. The User is solely responsible for the content, legality, confidentiality, and rights relating to uploaded User files.",
        "7.4. Personal data processing is governed by the Privacy Policy at /polityka-prywatnosci.",
      ],
    },
    {
      title: "§8. Permitted and prohibited use",
      paragraphs: [
        "8.1. The User must use the Service lawfully, in accordance with these Terms and good practice.",
        "8.2. The following is prohibited in particular:",
      ],
      list: [
        "uploading illegal content or content infringing third-party rights, including copyright, industrial property, personality rights, or trade secrets;",
        "processing materials the User is not authorized to use (e.g. protected music, films, software);",
        "using the Service to download, convert, or distribute content from streaming platforms, social media, or other sources in violation of those platforms' terms or the law;",
        "uploading viruses, malware, exploits, or files intended to damage the Service or other users' devices;",
        "automated, mass, or excessive use (bots, scrapers, server overload), including bypassing technical limits;",
        "attempting unauthorized access to Service systems, other users' Accounts, or Provider infrastructure;",
        "impersonating another person or entity or misrepresenting affiliation with the Provider;",
        "using AI tools to generate illegal, discriminatory, misleading content or content infringing third-party rights.",
      ],
    },
    {
      title: "§9. Artificial intelligence (AI) tools",
      paragraphs: [
        "9.1. AI tools generate content automatically using external models. The Provider does not guarantee the accuracy, completeness, currency, or fitness of Generated content for any particular purpose.",
        "9.2. AI-generated content is not professional advice (legal, medical, financial, technical). Users must verify results before use.",
        "9.3. The User is fully responsible for how Generated content is used, including any copyright infringement. The Provider does not claim ownership of User files or Generated content belonging to the User under applicable law.",
        "9.4. The Provider may impose daily limits, moderation, or temporary disabling of AI tools in case of abuse, infrastructure overload, or AI provider requirements.",
      ],
    },
    {
      title: "§10. Audio extraction and download tools",
      paragraphs: [
        "10.1. The Service allows extracting audio tracks from video files uploaded by the User (e.g. own recordings, materials the User has rights to).",
        "10.2. The Service is not for downloading content from streaming services, VOD platforms, social media, or other sources in ways that violate copyright or platform terms. The User represents they have the right to process uploaded materials.",
        "10.3. The Provider does not verify the source of uploaded files but may block access upon reports of legal violations or serious abuse.",
      ],
    },
    {
      title: "§11. Advertising",
      paragraphs: [
        "11.1. The Service may display ads, including Google AdSense, to support free tools and development.",
        "11.2. Ad providers (including Google) may use cookies and similar technologies per the Privacy Policy and their own policies. Users can manage cookie consent via the Service banner and browser settings.",
        "11.3. Ad content is supplied by third parties. The Provider is not liable for ad content or advertisers' products/services.",
      ],
    },
    {
      title: "§12. Copyright and intellectual property",
      paragraphs: [
        "12.1. The Toolando.tech name, logo, Service layout, texts, tool descriptions, guides, and source code are protected. Commercial copying without Provider consent is prohibited.",
        "12.2. Users retain rights to User files. Uploading does not transfer copyright to the Provider.",
        "12.3. The User grants the Provider a non-exclusive, royalty-free license for the time necessary to technically process User files solely to perform the requested operation.",
        "12.4. Copying, reverse engineering, decompiling, or automated scraping of the Service without written consent is prohibited.",
      ],
    },
    {
      title: "§13. Provider liability",
      paragraphs: [
        "13.1. The Service is provided without warranties of any kind to the fullest extent permitted by law.",
        "13.2. The Provider is not liable for:",
      ],
      list: [
        "consequences of the User's use of Generated or converted content;",
        "data loss due to User actions, User device failure, or force majeure;",
        "Service interruptions due to maintenance, hosting/cloud failures, or Internet outages;",
        "indirect damages, lost profits, loss of reputation or data, to the extent permitted by law;",
        "actions of third parties (Stripe, Google, AI providers, hosting).",
      ],
    },
    {
      title: "§14. Force majeure",
      paragraphs: [
        "14.1. The Provider is not liable for failure or improper performance due to force majeure, including critical infrastructure failures, natural disasters, war, strikes, epidemics, government decisions, or mass IT attacks.",
      ],
    },
    {
      title: "§15. Complaints",
      paragraphs: [
        "15.1. Complaints about the Service, Premium subscriptions, or Terms violations may be sent to {{email}}.",
        "15.2. A complaint should describe the problem, date of occurrence, and information identifying the User (Account email).",
        "15.3. The Provider responds within 14 days of receipt unless special rules require a different period.",
        "15.4. Consumers may use out-of-court dispute resolution, including the EU ODR platform: https://ec.europa.eu/consumers/odr",
      ],
    },
    {
      title: "§16. Changes to Terms and Service",
      paragraphs: [
        "16.1. The Provider may change these Terms for important reasons, including legal changes, Service feature changes, new tools, or business model changes.",
        "16.2. Registered Users will be notified of material Terms changes at least 14 days in advance by email or Service notice, unless law requires a longer period.",
        "16.3. Continued use after changes take effect means acceptance. If you do not accept changes, stop using the Service and cancel Premium before the next billing period.",
      ],
    },
    {
      title: "§17. Final provisions",
      paragraphs: [
        "17.1. Polish law applies to matters not covered by these Terms, including the Civil Code and Consumer Rights Act for consumers.",
        "17.2. Disputes are resolved by courts with jurisdiction under generally applicable rules. For consumers, mandatory consumer protection rules on jurisdiction apply.",
        "17.3. If any provision is invalid, the remaining provisions remain in force. Invalid provisions are replaced by applicable statutory rules.",
        "17.4. These Terms take effect upon publication on the Service. The current version is always available at /regulamin.",
      ],
    },
  ],
  footerNote:
    "For Terms, complaints, or consumer rights matters, contact {{email}}. The Privacy Policy is an integral supplement to these Terms.",
}
